add weather bash script instead of nodejs script.

diff --git a/linux/i3/scripts/weather b/linux/i3/scripts/weather
--- a/linux/i3/scripts/weather
+++ b/linux/i3/scripts/weather
@@ -1,3 +1,30 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-NODE_PATH=/usr/local/lib/node_modules node ~/.config/i3/scripts/weather.js
+command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.  Aborting."; exit 1; }
+command -v wget >/dev/null 2>&1 || { echo >&2 "Program 'wget' required but is not installed.  Aborting."; exit 1; }
+
+APIKEY="c7cee422559a135db5f0259e791dfae3"
+ZIPCODE="30115"
+URL="http://api.openweathermap.org/data/2.5/weather?zip=${ZIPCODE}&units=imperial&APPID=${APIKEY}"
+
+WEATHER_RESPONSE=$(wget -qO- "${URL}")
+
+WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.weather[0].main' | sed 's/"//g')
+WEATHER_TEMP=$(echo $WEATHER_RESPONSE | jq '.main.temp')
+
+case $WEATHER_CONDITION in
+  'Clouds')
+    WEATHER_ICON=""
+    ;;
+  'Rain')
+    WEATHER_ICON=""
+    ;;
+  'Snow')
+    WEATHER_ICON=""
+    ;;
+  *)
+    WEATHER_ICON=""
+    ;;
+esac
+
+echo "${WEATHER_ICON} ${WEATHER_TEMP}°F"
